//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapSyncAssembly
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SubscriptionEntities : DbContext
    {
        public SubscriptionEntities()
            : base("name=SubscriptionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SS_Tbl_ClientStatus> SS_Tbl_ClientStatus { get; set; }
        public virtual DbSet<SS_Tbl_Config> SS_Tbl_Config { get; set; }
        public virtual DbSet<SS_Tbl_ConnectionStatus> SS_Tbl_ConnectionStatus { get; set; }
        public virtual DbSet<SS_Tbl_Error> SS_Tbl_Error { get; set; }
        public virtual DbSet<SS_Tbl_Language> SS_Tbl_Language { get; set; }
        public virtual DbSet<SS_Tbl_Message> SS_Tbl_Message { get; set; }
        public virtual DbSet<SS_Tbl_MessageLog> SS_Tbl_MessageLog { get; set; }
        public virtual DbSet<SS_Tbl_MessageLogIncoming> SS_Tbl_MessageLogIncoming { get; set; }
        public virtual DbSet<SS_Tbl_Promotion_Group> SS_Tbl_Promotion_Group { get; set; }
        public virtual DbSet<SS_Tbl_Promotion_Schedule> SS_Tbl_Promotion_Schedule { get; set; }
        public virtual DbSet<SS_Tbl_Promotion_Temp> SS_Tbl_Promotion_Temp { get; set; }
        public virtual DbSet<SS_Tbl_Role> SS_Tbl_Role { get; set; }
        public virtual DbSet<SS_Tbl_Schedule> SS_Tbl_Schedule { get; set; }
        public virtual DbSet<SS_Tbl_Settings> SS_Tbl_Settings { get; set; }
        public virtual DbSet<SS_Tbl_SiteMap> SS_Tbl_SiteMap { get; set; }
        public virtual DbSet<SS_Tbl_SubCategory> SS_Tbl_SubCategory { get; set; }
        public virtual DbSet<SS_Tbl_Subscription> SS_Tbl_Subscription { get; set; }
        public virtual DbSet<SS_Tbl_User> SS_Tbl_User { get; set; }
    }
}
