//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapSyncAssembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Tbl_MessageLog
    {
        public int Id { get; set; }
        public int FromAddress { get; set; }
        public string ToAddress { get; set; }
        public Nullable<int> MessageId { get; set; }
        public string Status { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Reference { get; set; }
        public string MessageBody { get; set; }
    
        public virtual SS_Tbl_Message SS_Tbl_Message { get; set; }
        public virtual SS_Tbl_User SS_Tbl_User { get; set; }
    }
}
