//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapSyncAssembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Tbl_Subscription
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int SubCategoryId { get; set; }
        public Nullable<System.DateTime> DateSubscription { get; set; }
        public Nullable<System.DateTime> DateTermination { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Mobile { get; set; }
        public string Product_Id { get; set; }
    
        public virtual SS_Tbl_SubCategory SS_Tbl_SubCategory { get; set; }
    }
}
