//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapSyncAssembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Tbl_SubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SS_Tbl_SubCategory()
        {
            this.SS_Tbl_Schedule = new HashSet<SS_Tbl_Schedule>();
            this.SS_Tbl_Subscription = new HashSet<SS_Tbl_Subscription>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string KeyWord { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<bool> isDefault { get; set; }
    
        public virtual SS_Tbl_Language SS_Tbl_Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_Tbl_Schedule> SS_Tbl_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_Tbl_Subscription> SS_Tbl_Subscription { get; set; }
    }
}
