//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapSyncAssembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Tbl_SiteMap
    {
        public int Sid { get; set; }
        public string MenuId { get; set; }
        public Nullable<int> Role { get; set; }
    
        public virtual SS_Tbl_Role SS_Tbl_Role { get; set; }
    }
}
