//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapSyncAssembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Tbl_MessageLogIncoming
    {
        public int Id { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string MessageBody { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
