//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapSyncAssembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Tbl_Schedule
    {
        public int ScheduleID { get; set; }
        public int Sender { get; set; }
        public Nullable<int> Receiver { get; set; }
        public int MessageID { get; set; }
        public string DateSchedule { get; set; }
        public Nullable<int> Status { get; set; }
        public string LastModified { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual SS_Tbl_Message SS_Tbl_Message { get; set; }
        public virtual SS_Tbl_SubCategory SS_Tbl_SubCategory { get; set; }
    }
}
