//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapSyncAssembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Tbl_Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SS_Tbl_Message()
        {
            this.SS_Tbl_MessageLog = new HashSet<SS_Tbl_MessageLog>();
            this.SS_Tbl_Promotion_Schedule = new HashSet<SS_Tbl_Promotion_Schedule>();
            this.SS_Tbl_Schedule = new HashSet<SS_Tbl_Schedule>();
        }
    
        public int MessageID { get; set; }
        public int Sender { get; set; }
        public Nullable<int> ReceiverGroup { get; set; }
        public string MessageBody { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Destination { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_Tbl_MessageLog> SS_Tbl_MessageLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_Tbl_Promotion_Schedule> SS_Tbl_Promotion_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_Tbl_Schedule> SS_Tbl_Schedule { get; set; }
    }
}
